name: 'Publish release'

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'The version you want to publish to NPM'
        options:
          - patch
          - minor

permissions:
  contents: write

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up SSH key
        run: |
          # Create SSH directory
          mkdir -p ~/.ssh

          # Add the private SSH key from secrets
          echo "${{ secrets.RELEASINGAPP }}" > ~/.ssh/id_rsa

          # Set the correct permissions for the SSH key
          chmod 600 ~/.ssh/id_rsa

          # Add GitHub to known hosts to avoid SSH prompts
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Verify SSH connection
        run: |
          ssh -T git@github.com

      - name: Use GitHub CLI (gh)
        run: |
          gh auth status
          gh repo list

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: ./scripts/publish.sh --publish=false
        env:
          VERSION: ${{ github.event.inputs.version }}
          DIST_TAG: 'latest'
          GITHUB_ACTOR: ${{ github.actor }}
