name: 'Publish release'

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'The version you want to publish to NPM'
        options:
          - patch
          - minor

permissions:
  contents: write

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASINGAPP }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: ./scripts/publish.sh --publish=false
        env:
          VERSION: ${{ github.event.inputs.version }}
          DIST_TAG: 'latest'
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{steps.app-token.outputs.token}}
